create table stores
(
    id   bigint generated by default as identity
        constraint pk_stores
            primary key,
    name varchar(255) not null
        constraint uc_stores_name
            unique
);

alter table stores
    owner to postgres;

create table products
(
    id               varchar(255)     not null
        constraint pk_products
            primary key,
    product_name     varchar(255)     not null,
    product_category varchar(255)     not null,
    brand            varchar(255)     not null,
    package_quantity double precision not null,
    package_unit     varchar(255)     not null
);

alter table products
    owner to postgres;

create table prices
(
    id         bigint generated by default as identity
        constraint pk_prices
            primary key,
    product_id varchar(255)     not null
        constraint fk_prices_on_product
            references products,
    store_id   bigint           not null
        constraint fk_prices_on_store
            references stores,
    price      double precision not null,
    currency   varchar(255)     not null,
    date       date             not null
);

alter table prices
    owner to postgres;

create table discounts
(
    id                     bigint generated by default as identity
        constraint pk_discounts
            primary key,
    product_id             varchar(255)     not null
        constraint fk_discounts_on_product
            references products,
    store_id               bigint           not null
        constraint fk_discounts_on_store
            references stores,
    percentage_of_discount double precision not null,
    start_date             date             not null,
    end_date               date             not null
);

alter table discounts
    owner to postgres;

create table price_alerts
(
    id                bigint generated by default as identity
        constraint pk_price_alerts
            primary key,
    user_email        varchar(255)     not null,
    product_id        varchar(255)     not null
        constraint fk_price_alerts_on_product
            references products,
    store_id          bigint
        constraint fk_price_alerts_on_store
            references stores,
    target_price      double precision not null,
    currency          varchar(255)     not null,
    status            varchar(255)     not null,
    created_date      date             not null,
    last_checked_date date             not null
);

alter table price_alerts
    owner to postgres;

